export const USER_GET_AUTH2_REQUEST = 'USER_GET_AUTH2_REQUEST';
export const USER_GET_AUTH2_SUCCESS = 'USER_GET_AUTH2_SUCCESS';
export const USER_GET_AUTH2_FAILED = 'USER_GET_AUTH2_FAILED';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

export const GET_USER_DETAIL_REQUEST = 'GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILED = 'GET_USER_DETAIL_FAILED';

export const UPDATE_USER_DETAIL_REQUEST = 'UPDATE_USER_DETAIL_REQUEST';
export const UPDATE_USER_DETAIL_SUCCESS = 'UPDATE_USER_DETAIL_SUCCESS';
export const UPDATE_USER_DETAIL_FAILED = 'UPDATE_USER_DETAIL_FAILED';

export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_FAILED = 'GET_REQUESTS_FAILED';

export const CREATE_NEW_REQUEST_REQUEST = 'CREATE_NEW_REQUEST_REQUEST';
export const CREATE_NEW_REQUEST_SUCCESS = 'CREATE_NEW_REQUEST_SUCCESS';
export const CREATE_NEW_REQUEST_FAILED = 'CREATE_NEW_REQUEST_FAILED';

export const SET_LOCAL_STORAGE_AUTH2_INFO = 'SET_LOCAL_STORAGE_AUTH2_INFO';
export const RESET_LOCAL_STORAGE_AUTH2_INFO = 'RESET_LOCAL_STORAGE_AUTH2_INFO';

export const SET_LOCAL_STORAGE_USER_INFO = 'SET_LOCAL_STORAGE_USER_INFO';
export const RESET_LOCAL_STORAGE_USER_INFO = 'RESET_LOCAL_STORAGE_USER_INFO';

export const CHECK_EMAIL_EXISTING_REQUEST = 'CHECK_EMAIL_EXISTING_REQUEST';
export const CHECK_EMAIL_EXISTING_SUCCESS = 'CHECK_EMAIL_EXISTING_SUCCESS';
export const CHECK_EMAIL_EXISTING_FAILED = 'CHECK_EMAIL_EXISTING_FAILED';

export const UPLOAD_ATTACHMENT_REQUEST = 'UPLOAD_ATTACHMENT_REQUEST';
export const UPLOAD_ATTACHMENT_SUCCESS = 'UPLOAD_ATTACHMENT_SUCCESS';
export const UPLOAD_ATTACHMENT_FAILED = 'UPLOAD_ATTACHMENT_FAILED';

export const GET_ATTACHMENTS_REQUEST = 'GET_ATTACHMENTS_REQUEST';
export const GET_ATTACHMENTS_SUCCESS = 'GET_ATTACHMENTS_SUCCESS';
export const GET_ATTACHMENTS_FAILED = 'GET_ATTACHMENTS_FAILED';

export const GET_ATTACHMENT_BODY_REQUEST = 'GET_ATTACHMENT_BODY_REQUEST';
export const GET_ATTACHMENT_BODY_SUCCESS = 'GET_ATTACHMENT_BODY_SUCCESS';
export const GET_ATTACHMENT_BODY_FAILED = 'GET_ATTACHMENT_BODY_FAILED';
