export const USER_GET_AUTH2_REQUEST = 'USER_GET_AUTH2_REQUEST';
export const USER_GET_AUTH2_SUCCESS = 'USER_GET_AUTH2_SUCCESS';
export const USER_GET_AUTH2_FAILED = 'USER_GET_AUTH2_FAILED';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const GET_DOCTORS_REQUEST = 'GET_DOCTORS_REQUEST';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const GET_DOCTORS_FAILED = 'GET_DOCTORS_FAILED';

export const GET_USER_DETAIL_REQUEST = 'GET_USER_DETAIL_REQUEST';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAILED = 'GET_USER_DETAIL_FAILED';

export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_FAILED = 'GET_REQUESTS_FAILED';

export const CREATE_NEW_REQUEST_REQUEST = 'CREATE_NEW_REQUEST_REQUEST';
export const CREATE_NEW_REQUEST_SUCCESS = 'CREATE_NEW_REQUEST_SUCCESS';
export const CREATE_NEW_REQUEST_FAILED = 'CREATE_NEW_REQUEST_FAILED';

export const SET_LOCAL_STORAGE_AUTH2_INFO = 'SET_LOCAL_STORAGE_AUTH2_INFO';
export const RESET_LOCAL_STORAGE_AUTH2_INFO = 'RESET_LOCAL_STORAGE_AUTH2_INFO';

export const SET_LOCAL_STORAGE_USER_INFO = 'SET_LOCAL_STORAGE_USER_INFO';
export const RESET_LOCAL_STORAGE_USER_INFO = 'RESET_LOCAL_STORAGE_USER_INFO';

export const CHECK_EMAIL_EXISTING_REQUEST = 'CHECK_EMAIL_EXISTING_REQUEST';
export const CHECK_EMAIL_EXISTING_SUCCESS = 'CHECK_EMAIL_EXISTING_SUCCESS';
export const CHECK_EMAIL_EXISTING_FAILED = 'CHECK_EMAIL_EXISTING_FAILED';