export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const GET_DOCTORS_REQUEST = 'GET_DOCTORS_REQUEST';
export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const GET_DOCTORS_FAILED = 'GET_DOCTORS_FAILED';

export const GET_DOCTOR_DETAIL_REQUEST = 'GET_DOCTOR_DETAIL_REQUEST';
export const GET_DOCTOR_DETAIL_SUCCESS = 'GET_DOCTOR_DETAIL_SUCCESS';
export const GET_DOCTOR_DETAIL_FAILED = 'GET_DOCTOR_DETAIL_FAILED';

export const GET_REQUESTS_REQUEST = 'GET_REQUESTS_REQUEST';
export const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_FAILED = 'GET_REQUESTS_FAILED';

export const CREATE_NEW_REQUEST_REQUEST = 'CREATE_NEW_REQUEST_REQUEST';
export const CREATE_NEW_REQUEST_SUCCESS = 'CREATE_NEW_REQUEST_SUCCESS';
export const CREATE_NEW_REQUEST_FAILED = 'CREATE_NEW_REQUEST_FAILED';